# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  greengrass-version: 1.9.3

steps:
- task: Docker@2
  displayName: Login to Docker Hub
  inputs:
    command: login
    containerRegistry: Dockerhub
- script: |
    docker run --rm --privileged multiarch/qemu-user-static:register --reset
    docker build -t "wagoautomation/aws-iot-greengrass:$(greengrass-version)" --build-arg "greengrass_version=$(greengrass-version)" ./build-context
    docker tag wagoautomation/aws-iot-greengrass:$(greengrass-version) wagoautomation/aws-iot-greengrass:latest 
    docker push wagoautomation/aws-iot-greengrass:$(greengrass-version)
    docker push wagoautomation/aws-iot-greengrass:latest
