# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  greengrass-version: 1.8.1

steps:
- task: Docker@2
  displayName: Login to Docker Hub
  inputs:
    command: login
    containerRegistry: Dockerhub
- script: docker run --rm --privileged multiarch/qemu-user-static:register --reset
- task: Docker@2
  displayName: buildAndPush
  inputs:
    containerRegistry: 'Dockerhub'
    repository: 'wagoautomation/aws-iot-greengrass'
    command: 'buildAndPush'
    Dockerfile: './build-context/Dockerfile'
    buildContext: './build-context'
    tags: '$(greengrass-version)'
