version: '3.7'

services:
  greengrass:
    init: true
    build:
      context: .
      args:
        greengrass_version: $GREENGRASS_VERSION
        os_platform: $PLATFORM
    container_name: aws-iot-greengrass
    image: $PLATFORM/aws-iot-greengrass:$GREENGRASS_VERSION
    volumes:
      - ./certs:/greengrass/certs
      - ./config:/greengrass/config
      - ./deployment:/greengrass/ggc/deployment
      - ./log:/greengrass/ggc/var/log
    ports:
      - "8883:8883"
    entrypoint: "/greengrass-entrypoint.sh"
