name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      gg-version:
        required: true
        default: "1.11.6"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the slim Docker image
      run: docker buildx build --platform=linux/arm/v7 --build-arg greengrass_version=${{ github.event.inputs.gg-version }}
           --target=slim -t wagoautomation/aws-iot-greengrass:${{ github.event.inputs.gg-version }}-slim build-context/ --push
    - name: Build the full Docker image
      run: docker buildx build --platform=linux/arm/v7 --build-arg greengrass_version=${{ github.event.inputs.gg-version }}
           --target=full -t wagoautomation/aws-iot-greengrass:${{ github.event.inputs.gg-version }}-full build-context/ --push
